// File generated by FlutterFire CLI (manually from firebase apps:sdkconfig).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX0gopO5JV1PicUUlyRkcolVTrZ406ruw',
    appId: '1:607717506492:web:1f669174c3a6ea34327fb9',
    messagingSenderId: '607717506492',
    projectId: 'pet-app-3718c',
    authDomain: 'pet-app-3718c.firebaseapp.com',
    storageBucket: 'pet-app-3718c.firebasestorage.app',
    measurementId: 'G-55FDF1XYFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqVCAQ4qszoTjq3ZLrb-9NBkmfXfXJJO0',
    appId: '1:607717506492:android:10acfa88d002ffef327fb9',
    messagingSenderId: '607717506492',
    projectId: 'pet-app-3718c',
    storageBucket: 'pet-app-3718c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqDkSiVmbiRlWqf-rT14Zqvyr46ke16Vg',
    appId: '1:607717506492:ios:f46651c2f5b0b828327fb9',
    messagingSenderId: '607717506492',
    projectId: 'pet-app-3718c',
    storageBucket: 'pet-app-3718c.firebasestorage.app',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqDkSiVmbiRlWqf-rT14Zqvyr46ke16Vg',
    appId: '1:607717506492:ios:f46651c2f5b0b828327fb9',
    messagingSenderId: '607717506492',
    projectId: 'pet-app-3718c',
    storageBucket: 'pet-app-3718c.firebasestorage.app',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX0gopO5JV1PicUUlyRkcolVTrZ406ruw',
    appId: '1:607717506492:web:1f669174c3a6ea34327fb9',
    messagingSenderId: '607717506492',
    projectId: 'pet-app-3718c',
    authDomain: 'pet-app-3718c.firebaseapp.com',
    storageBucket: 'pet-app-3718c.firebasestorage.app',
    measurementId: 'G-55FDF1XYFE',
  );
}
